deployments:
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzdmNjI0NTMyLTViMzYtNDc3Zi1iOWZmLTc4MWFkNGJjM2NiMS9lN2MzMWE3Yy0wNjIwLTExZjAtYWYxOS0wYWZmZjNkZDM0Nzc=
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzdmNjI0NTMyLTViMzYtNDc3Zi1iOWZmLTc4MWFkNGJjM2NiMS8wODgxZjhhNi0wNThmLTExZjAtODExOC0wYWZmZjNkZDM0Nzc=
