deployments:
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzdhMjM5NzNiLTM2MjctNGQxNy1hMDAyLWY4Y2M0NDM4YTUzNi83NmI4ZTI5NC0xMzcyLTExZjAtOTE2ZS0wYWZmZjI1ZmQ5MzM=
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzdhMjM5NzNiLTM2MjctNGQxNy1hMDAyLWY4Y2M0NDM4YTUzNi8zYjc1YjNmOC0xMzc1LTExZjAtYTE2Zi0wYWZmZjI1ZmQ5MzM=
