name: Simple CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: echo "Building the project..."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo "Running tests..."
  deploy-stg:
    runs-on: ubuntu-latest
    needs: test
    environment: Staging
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to environment..."   
  deploy-Stg:
    runs-on: ubuntu-latest
    needs: test
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to environment..."      
  deploy-prd:
    runs-on: ubuntu-latest
    needs: test
    environment: Production
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to environment..."
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to environment..."
